# Generated by Django 4.2.4 on 2023-08-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
