# Generated by Django 4.2.4 on 2023-08-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_useraccount_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="image",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
